global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['localhost:3000']    

  - job_name: 'coordinator'
    static_configs:
      - targets: ['localhost:3001']     

  - job_name: 'email_worker'
    static_configs:
      - targets: ['localhost:3002']     
